Repository ctc-oss/daffodil-vscode, pull requests merged in 2022-05, with the labels that each got.

#62 integrate cursor position (offset) reporting and changing
  package.json
  src/adapter/extension.ts
  src/omega_edit/client.ts
  src/position.ts
Labels: UI, editing

#61 SonarLint: fix 2 await lints
  src/daffodilDebugger.ts
  src/hexView.ts
Labels: code quality

#65 Save Session File -- No Prompt
  package.json
  src/omega_edit/client-exp.ts
  src/omega_edit/client.ts
  src/omega_edit/scripts/omega_edit.js
  src/omega_edit/utils/misc.ts
Labels: editing
