Repository ctc-oss/daffodil-vscode, pull requests merged in 2022-04, with the labels that each got.

#49 Intellisense and syntax colorization enhancements
  .vscodeignore
  language/dfdl.json
  language/json-license.txt
  language/syntax.json
  language/syntaxes/dfdl.tmLanguage.json
  package.json
  project/Rat.scala
  snippets/dfdl.json
  src/adapter/activateDaffodilDebug.ts
  src/language/README.md
  src/language/dfdl.ts
Labels: enhancement, intellisense, syntax highlighting

#50 Semantic enhancements
  .vscodeignore
  LICENSE
  build.sbt
  language/syntaxes/dfdl.tmLanguage.json
  package.json
  project/Rat.scala
  src/adapter/activateDaffodilDebug.ts
  src/language/interfaces/commands.ts
  src/language/interfaces/configuration.ts
  src/language/interfaces/interfaces.d.ts
  src/language/interfaces/tagLexer.ts
  src/language/interfaces/tagMatcher.ts
  src/language/interfaces/tagParser.ts
  src/language/interfaces/tagStyler.ts
  src/language/semantics/dfdlExt.ts
  src/language/semantics/diagnostics.ts
  src/language/semantics/documentChangeHandler.ts
  src/language/semantics/functionData.ts
  src/language/semantics/languageConfigurations.ts
  src/language/semantics/schSchema.ts
  src/language/semantics/schemaQuery.ts
  src/language/semantics/xPathDocumentChangeHandler.ts
  src/language/semantics/xmlSnippets.ts
  src/language/semantics/xpLexer.ts
  src/language/semantics/xslLexer.ts
  src/language/semantics/xslLexerLight.ts
  src/language/semantics/xslLexerRenameTag.ts
  src/language/semantics/xsltSchema.ts
  src/language/semantics/xsltSchema4.ts
  src/language/semantics/xsltSnippets.ts
  src/language/semantics/xsltTokenCompletions.ts
  src/language/semantics/xsltTokenDiagnostics.ts
Labels: enhancement

#52 Merge with upstream
  .gitignore
  LICENSE
  src/omegaEdit/demoClient.ts
  src/omegaEdit/omegaUtils.ts
  src/omegaEdit/server.ts
Labels: legal

#58 OS specific build
  .github/workflows/tests.yml
  LICENSE
  NOTICE
  package.json
  yarn.lock
Labels: testing, CI, cross-platform
